# Generated by Django 4.1.5 on 2023-01-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField()),
                ('data_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
