# Generated by Django 4.1.5 on 2023-01-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
