# Generated by Django 4.1.5 on 2023-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tracker', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
