# Generated by Django 4.1.5 on 2023-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tracker', '0003_alter_users_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
